---
- hosts: all
  become: true
  --ask-pass: true
  
  tasks:
    - name: stop previous version docker
      shell: docker stop mini-project
    - name: remove stopped container
      shell: docker rm -f mini-project
    - name: remove docker images
      shell: docker image rm -f abhijain614/demorepo:latest
    - name: create docker image
      shell: docker run -it --name mini-project abhijain614/demorepo:latest
